language: node_js

node_js:
  - node

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run lint

after_success:
  - npm run build
  - npm run deploy
